services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./app/:/go/src/app

volumes:
  dbdata: null
