services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    expose:
      - '8080'
    volumes:
      - ./app/:/go/src/app

  nginx:
    image: nginx:latest
    build:
      context: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
volumes:
  dbdata: null
